# Generated by Django 3.1.3 on 2020-11-18 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formcomplaint',
            name='Complaint_name',
            field=models.TextField(),
        ),
    ]
