# Generated by Django 3.1.3 on 2020-11-18 20:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miniproject1', '0003_auto_20201119_0129'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedbacks',
        ),
    ]
